base_branch: origin/main
log_dir: .gauntlet_logs
fail_fast: false

entry_points:
  - path: "."
    reviews:
      - code-quality

  - path: "apps/api"
    checks:
      - linter
      - packwerk
      - specs

  - path: "engines/*"
    checks:
      - linter
      - packwerk
      - specs
    reviews:
      - architecture
